FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Events

This is a service for managing relationships between areas, and allowing creating reservations.

It will be accessed through [an Ember app](//github.com/oakscastle/event).